// Official Perpl Exchange event entries: https://raw.githubusercontent.com/PerplFoundation/dex-sdk/main/crates/sdk/abi/dex/Exchange.json
// Source SHA-256: 766fc81326bdf27f243ca582f65c3e2ff72bc639d88674876697a63ae1c47cb3
// Generated 2026-10-07; review changes before updating.
export const exchangeEvents = [
  {
    type: 'event',
    name: 'AccountCreated',
    inputs: [
      {
        name: 'account',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'id',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CollateralDeposit',
    inputs: [
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'amountCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'balanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CollateralWithdrawal',
    inputs: [
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'amountCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'balanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ExchangeInitialized',
    inputs: [
      {
        name: 'sender',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'collateralToken',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'collateralDecimals',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'minAccountOpenCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'wrlsThousandthsTvl',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'wrlsMinWithdrawLimitCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'recycleFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'whitelistingEnabled',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FundingEventCompleted',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'fundingEventBlock',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'specifiedRatePct100k',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'actualRatePct100k',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'fundingPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'fundingPaymentPNS',
        type: 'int48',
        indexed: false,
        internalType: 'int48',
      },
      {
        name: 'fundingSumPNS',
        type: 'int48',
        indexed: false,
        internalType: 'int48',
      },
      {
        name: 'allowOverwrite',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'IncreasePositionCollateral',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'amountCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'balanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Initialized',
    inputs: [
      {
        name: 'version',
        type: 'uint8',
        indexed: false,
        internalType: 'uint8',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MakerOrderFilled',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'orderId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'lotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'feeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'lockedBalanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'amountCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'balanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MakerOrderFilledV2',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'orderId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'lotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'feeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'lockedBalanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'amountCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'balanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'builderId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'builderFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MarkUpdated',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionClosed',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'pricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'deltaPnlCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'fundingCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionCollateralDecreased',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'markPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'impactAdjPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'startDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'startEntryPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endEntryPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'effBmfHdths',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'decreaseCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'balanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionDecreased',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'startDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'startLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'deltaPnlCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'fundingCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionDeleveraged',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'forceClose',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'entryPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'markPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'deleveragePricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'deltaPnlCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'fundingCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'startDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'startLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'amountCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'balanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionDeleveragedV2',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'forceClose',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'entryPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'markPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'deleveragePricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'deltaPnlCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'fundingCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'startDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'startLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'amountCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'balanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'priceResiduePNSQ16',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionIncreased',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'leverageHdths',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'startDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pnlCollateralizedCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'premiumPnlSettledCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'maxNegPnlCollatBPS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'startLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'insFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'protFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionIncreasedV2',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'leverageHdths',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'startDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pnlCollateralizedCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'premiumPnlSettledCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'maxNegPnlCollatBPS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'startLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'insFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'protFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'priceResiduePNSQ16',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionInverted',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'leverageHdths',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'startDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pnlCollateralizedCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'pricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'startLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'endLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'deltaPnlCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'fundingCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'insFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'protFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionLiquidated',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'posAccountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'markPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'liqPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'liqLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'posLotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'deltaPnlCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'fundingCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'posAmountCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'posDepositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accAmountCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'accBalanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'onOrderBook',
        type: 'bool',
        indexed: false,
        internalType: 'bool',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionOpened',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'leverageHdths',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'depositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pnlCollateralizedCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'pricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'lotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'insFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'protFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionOpenedV2',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'leverageHdths',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'depositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pnlCollateralizedCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'pricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'lotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'insFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'protFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'priceResiduePNSQ16',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionUnwound',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'markPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'pricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'lotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'depositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionFmvCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'paymentCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'balanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PositionUnwoundV2',
    inputs: [
      {
        name: 'perpId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'accountId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'markPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionType',
        type: 'uint8',
        indexed: false,
        internalType: 'enum PositionEnum',
      },
      {
        name: 'pricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'lotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'depositCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'positionFmvCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'paymentCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'balanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'priceResiduePNSQ16',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TakerOrderFilled',
    inputs: [
      {
        name: 'entryPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'collatPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pnlPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'lotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'feeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'amountCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'balanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TakerOrderFilledV2',
    inputs: [
      {
        name: 'entryPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'collatPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pnlPricePNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'lotLNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'feeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'amountCNS',
        type: 'int256',
        indexed: false,
        internalType: 'int256',
      },
      {
        name: 'balanceCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'builderId',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'builderFeeCNS',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Upgraded',
    inputs: [
      {
        name: 'implementation',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
] as const
