import type { NormalizedTelemetry } from '../../domain/src/index.js'
export type L2Level = { p: number; s: number; o: number }
export type OrderBookState = { bids: L2Level[]; asks: L2Level[]; timestamp: number; block?: number }
export type MarketStreamState = { book?: OrderBookState; fundingRate: number; market?: Record<string, unknown>; candleCloses: number[] }
export function applyMarketMessage(state: MarketStreamState, raw: unknown): MarketStreamState {
  if (!raw || typeof raw !== 'object') return state
  const message = raw as Record<string, unknown>; const at = (message.at ?? {}) as Record<string, unknown>
  if (message.mt === 15) { const value = message as { bid?: L2Level[]; ask?: L2Level[] }; return { ...state, book: { bids: value.bid ?? [], asks: value.ask ?? [], timestamp: Number(at.t ?? Date.now()), block: Number(at.b ?? 0) } } }
  if (message.mt === 16 && state.book) { const value = message as { bid?: L2Level[]; ask?: L2Level[] }; const merge = (current: L2Level[], updates: L2Level[] = []) => { const map = new Map(current.map(item => [item.p, item])); for (const item of updates) { if (item.o === 0) map.delete(item.p); else map.set(item.p, item) } return [...map.values()].sort((a, b) => b.p - a.p) }; return { ...state, book: { ...state.book, bids: merge(state.book.bids, value.bid), asks: merge(state.book.asks, value.ask), timestamp: Number(at.t ?? Date.now()), block: Number(at.b ?? state.book.block) } } }
  if (message.mt === 10) { const data = message.d as Record<string, unknown> | undefined; const candidate = data?.rate !== undefined ? data : Object.values(data ?? {}).find(value => value && typeof value === 'object' && 'rate' in (value as object)) as Record<string, unknown> | undefined; return { ...state, fundingRate: Number(candidate?.rate ?? 0) / 1_000_000 } }
  if (message.mt === 9) { const data = message.d as Record<string, unknown> | undefined; return { ...state, market: data && 'mrk' in data ? data : data?.[Object.keys(data)[0] ?? ''] as Record<string, unknown> } }
  if (message.mt === 11 || message.mt === 12) { const candles = Array.isArray(message.d) ? message.d as Array<Record<string, unknown>> : []; const closes = candles.map(item => Number(item.c ?? item.close)).filter(Number.isFinite); return { ...state, candleCloses: [...state.candleCloses, ...closes].slice(-120) } }
  return state
}
export function depthNotional(book: OrderBookState | undefined, levels = 10) { if (!book) return 0; return [...book.bids.slice(0, levels), ...book.asks.slice(0, levels)].reduce((sum, item) => sum + item.p * item.s, 0) }
export function realizedVolatility(closes: number[]) { if (closes.length < 2) return Number.NaN; const returns = closes.slice(1).map((close, index) => Math.log(close / closes[index])).filter(Number.isFinite); if (!returns.length) return Number.NaN; const mean = returns.reduce((a, b) => a + b, 0) / returns.length; return Math.sqrt(returns.reduce((sum, value) => sum + (value - mean) ** 2, 0) / returns.length) * Math.sqrt(returns.length) }
export function normalizeMarketStream(state: MarketStreamState, source: NormalizedTelemetry['source']): NormalizedTelemetry | null { if (!state.market) return null; const at = state.market.at as Record<string, unknown> | undefined; const mark = Number(state.market.mrk ?? 0); const bid = Number(state.market.bid ?? 0); const ask = Number(state.market.ask ?? 0); const timestamp = Number(at?.t ?? state.market.timestamp ?? 0); if (!(mark > 0 && bid > 0 && ask >= bid && timestamp > 0)) return null; return { mark, oracle: Number(state.market.orl ?? mark), bid, ask, mid: Number(state.market.mid ?? (bid + ask) / 2), spreadBps: (ask - bid) / ((ask + bid) / 2) * 10000, fundingRate: state.fundingRate, depthNotional: depthNotional(state.book), volatility: realizedVolatility(state.candleCloses), volume24h: Number(state.market.dv ?? 0), openInterest: Number(state.market.oi ?? 0), block: Number(at?.b ?? state.market.block ?? state.book?.block ?? 0), timestamp, source, freshnessMs: Date.now() - timestamp, executionHealthy: true } }

