import type { NormalizedTelemetry } from '../../domain/src/index.js'
export type StreamHealth = { connected: boolean; lastMessageAt: number; lastSequence?: number; reconnects: number; stale: boolean }
export class PerplMarketStream { private stopped = false; private socket?: WebSocket; private reconnectTimer?: ReturnType<typeof setTimeout>; private attempts = 0; private healthState: StreamHealth = { connected: false, lastMessageAt: 0, reconnects: 0, stale: true }; constructor(private readonly url: string, private readonly chainId: number, private readonly streams: string[], private readonly onMessage: (message: unknown) => void, private readonly freshnessWindowMs = 10_000) {}
  start() { this.stopped = false; this.open() }
  stop() { this.stopped = true; if (this.reconnectTimer) clearTimeout(this.reconnectTimer); this.socket?.close(); this.socket = undefined; this.healthState = { ...this.healthState, connected: false, stale: true } }
  health() { return { ...this.healthState, stale: !this.healthState.lastMessageAt || Date.now() - this.healthState.lastMessageAt > this.freshnessWindowMs } }
  private open() { if (this.stopped) return; this.socket = new WebSocket(`${this.url}/ws/v1/market-data`); this.socket.onopen = () => { this.attempts = 0; this.healthState = { ...this.healthState, connected: true }; const streams = this.streams.includes(`heartbeat@${this.chainId}`) ? this.streams : [...this.streams, `heartbeat@${this.chainId}`]; this.socket?.send(JSON.stringify({ mt: 5, subs: streams.map(stream => ({ stream, subscribe: true })) })) }; this.socket.onmessage = event => { try { const message = JSON.parse(String(event.data)) as { sn?: number; mt?: number; h?: number; d?: Record<string, unknown> }; const previous = this.healthState.lastSequence; if (message.sn !== undefined && previous !== undefined && message.sn !== previous + 1 && message.mt !== 2) { this.healthState = { ...this.healthState, stale: true }; this.onMessage({ type: 'SEQUENCE_GAP', expected: previous + 1, received: message.sn }); } this.healthState = { ...this.healthState, lastMessageAt: Date.now(), lastSequence: message.sn ?? this.healthState.lastSequence, stale: false }; this.onMessage(message) } catch { this.onMessage({ type: 'MALFORMED_EVENT' }) } }; this.socket.onerror = () => this.socket?.close(); this.socket.onclose = () => { this.healthState = { ...this.healthState, connected: false, stale: true, reconnects: this.healthState.reconnects + 1 }; if (!this.stopped) { const delay = Math.min(30_000, 500 * 2 ** this.attempts++); this.reconnectTimer = setTimeout(() => this.open(), delay) } } }
}
export function normalizeMarketState(message: { d: Record<string, { at?: { b?: number; t?: number }; orl: number; mrk: number; bid: number; ask: number; mid: number; dv: number; oi: number; volatility?: number }> }, marketId: string, fundingRate: number, depthNotional: number, source: NormalizedTelemetry['source']): NormalizedTelemetry | null { const state = message.d[marketId]; if (!state || !state.mrk || !state.at?.t) return null; return { mark: state.mrk, oracle: state.orl, bid: state.bid, ask: state.ask, mid: state.mid, spreadBps: state.mid > 0 ? (state.ask - state.bid) / state.mid * 10000 : Infinity, fundingRate, depthNotional, volatility: state.volatility ?? Number.NaN, volume24h: state.dv, openInterest: state.oi, block: state.at.b ?? 0, timestamp: state.at.t, source, freshnessMs: Date.now() - state.at.t } }
