import { describe, expect, it } from 'vitest'
import { ExecutionWorker } from '../server/src/workers/execution-worker.js'
import type { Action, Book, Decision, NormalizedTelemetry, Position, Reserve } from '../packages/domain/src/index.js'
const book: Book = { id: 'b', userId: 'u', market: 'BTC', side: 'LONG', stance: 'DEFEND', liquidationFloor: 6, defenseCap: 100, timeLimitMs: 3600000, automationEnabled: true, status: 'ACTIVE', createdAt: new Date(Date.now() - 1000).toISOString(), updatedAt: new Date().toISOString() }
const position: Position = { bookId: 'b', side: 'LONG', size: 1, entryPrice: 100, markPrice: 98, liquidationPrice: 94, leverage: 6, unrealizedPnl: -2, margin: 16, timestamp: Date.now() }
const reserve: Reserve = { bookId: 'b', available: 100, reserved: 0, deployed: 0, cap: 100, updatedAt: new Date().toISOString() }
const telemetry: NormalizedTelemetry = { mark: 98, oracle: 98, bid: 97.9, ask: 98.1, mid: 98, spreadBps: 20, fundingRate: 0, depthNotional: 10000, volatility: 0.01, volume24h: 100, openInterest: 100, block: 1, timestamp: Date.now(), source: 'replay', freshnessMs: 1 }
function repo() { const actions: Action[]=[]; const events: unknown[]=[]; const decisions: Decision[]=[]; return { actions, events, decisions, getActionByIdempotency: async (key: string) => actions.find(a=>a.idempotencyKey===key) ?? null, getActiveAction: async (bookId: string) => actions.find(a=>a.bookId===bookId && ['QUEUED','VALIDATING','SUBMITTING','SUBMITTED','VERIFYING','UNKNOWN'].includes(a.status)) ?? null, saveAction: async (a: Action) => { const i=actions.findIndex(x=>x.id===a.id); if(i<0) actions.push({...a}); else actions[i]={...a} }, saveDecision: async (d: Decision) => { decisions.push(d) }, addEvent: async (e: unknown) => { events.push(e) }, getBookContext: async () => ({ book, position, reserve, priorDefenseEfficiency: Infinity, telemetry }), updateReserve: async () => undefined } }
describe('execution worker safety', () => { it('does not duplicate an idempotent action and records confirmed audit', async () => { const r=repo(); const venue={ submit: async (_a: Action) => ({ venueReference: 'venue-1', status: 'SUBMITTED' as const }), reconcile: async (a: Action) => ({ ...a, status: 'CONFIRMED' as const, confirmedAt: new Date().toISOString() }) }; const worker=new ExecutionWorker(r, venue); const decision=await worker.evaluate('b'); expect(decision.action).toBe('DEFEND'); const first=await worker.execute(decision); expect(first.status).toBe('CONFIRMED'); expect(r.actions).toHaveLength(1); expect((await worker.execute(decision)).id).toBe(first.id); expect(r.actions).toHaveLength(1); expect(r.events).toHaveLength(3) })
 it('keeps timeout unknown and does not treat it as failure', async () => { const r=repo(); const venue={ submit: async () => ({ venueReference: 'unknown', status: 'UNKNOWN' as const }), reconcile: async (a: Action) => a }; const worker=new ExecutionWorker(r, venue); const decision=await worker.evaluate('b'); const action=await worker.execute(decision); expect(action.status).toBe('UNKNOWN'); expect(action.error).toBe('VENUE_OUTCOME_UNKNOWN') }) })


