import { describe, expect, it } from 'vitest'
import { evaluate } from '../packages/risk-engine/src/index.js'
import type { Book, NormalizedTelemetry, Position, Reserve } from '../packages/domain/src/index.js'
const book: Book = { id: 'book', userId: 'user', market: 'BTC-PERP', side: 'LONG', stance: 'DEFEND', liquidationFloor: 6, defenseCap: 100, timeLimitMs: 8 * 60 * 60 * 1000, automationEnabled: true, status: 'ACTIVE', createdAt: new Date(Date.now() - 1000).toISOString(), updatedAt: new Date().toISOString() }
const position: Position = { bookId: 'book', side: 'LONG', size: 1, entryPrice: 100, markPrice: 100, liquidationPrice: 94, leverage: 6, unrealizedPnl: 0, margin: 16 }
const reserve: Reserve = { bookId: 'book', available: 300, reserved: 0, deployed: 0, cap: 100, updatedAt: new Date().toISOString() }
const telemetry = (overrides: Partial<NormalizedTelemetry> = {}): NormalizedTelemetry => ({ mark: 100, oracle: 100, bid: 99.99, ask: 100.01, mid: 100, spreadBps: 2, fundingRate: .0001, depthNotional: 5000, volatility: .01, volume24h: 10000, openInterest: 10000, block: 1, timestamp: Date.now(), source: 'replay', freshnessMs: 10, ...overrides })
describe('risk engine safety', () => { it('holds healthy state', () => expect(evaluate(book, position, reserve, telemetry()).state).toBe('HOLD')); it('defends below floor with executable liquidity', () => expect(evaluate(book, position, reserve, telemetry({ mark: 98 })).state).toBe('DEFEND')); it.each(['replay','perpl-rest','perpl-ws'] as const)('same live/replay sizing for %s', source => { const result = evaluate(book, position, reserve, telemetry({ mark: 98, source })); expect(result.state).toBe('DEFEND'); expect(result.amount).toBeGreaterThan(0) }); it('reduces when reserve is exhausted', () => expect(evaluate(book, position, { ...reserve, deployed: 100 }, telemetry({ mark: 98 })).state).toBe('REDUCE')); it('exits when defense was inefficient or liquidity collapses', () => { const result = evaluate(book, position, reserve, telemetry({ mark: 98, depthNotional: 100 }), .1); expect(result.state).toBe('EXIT'); expect(result.reasonCodes).toContain('DEFENSE_REFUSED') }); it('enters safe mode on stale state', () => expect(evaluate(book, position, reserve, telemetry({ freshnessMs: 20_000 })).state).toBe('SAFE_MODE')); it('exits on severe volatility spike', () => expect(evaluate(book, position, reserve, telemetry({ mark: 98, volatility: .25 })).state).toBe('EXIT')); it('handles short positions', () => expect(evaluate({ ...book, side: 'SHORT' }, { ...position, side: 'SHORT', liquidationPrice: 106 }, reserve, telemetry({ mark: 100 })).state).toBe('HOLD')); it('exits kill stance', () => expect(evaluate({ ...book, stance: 'KILL' }, position, reserve, telemetry()).state).toBe('EXIT')); it('exits at time limit', () => expect(evaluate({ ...book, timeLimitMs: 1, createdAt: new Date(Date.now() - 100).toISOString() }, position, reserve, telemetry()).state).toBe('EXIT')) })

