ALTER TABLE books ADD COLUMN IF NOT EXISTS safe_mode_reason text NULL
  CHECK (safe_mode_reason IN ('DATA_UNAVAILABLE','VENUE_UNAVAILABLE','UNRESOLVED_ACTION','RUNTIME_FAILURE'));
ALTER TABLE books ADD COLUMN IF NOT EXISTS safe_mode_since timestamptz NULL;
